version: '3'
services:
  docker_jenkins:
    restart: always
    image: jenkins/jenkins:lts
    container_name: docker_jenkins
    ports:
      - '8080:8080'
      - '50000:5000'
    volumes:
      - ~/jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock