
version: '3.5'
services:
  v2ray:
    image: v2ray/official:latest 
    container_name: v2ray
    restart: always
    volumes:
      - ./client.json:/etc/v2ray/client.json
      - ./server.json:/etc/v2ray/server.json
    ports:
      - "160:160"
      - "160:160/udp"
      - "201-220:201-220"
      - "201-220:201-220/udp"
    environment:
      - VMODE
    command: ["v2ray","-config=/etc/v2ray/${VMODE}.json"]