
version: '3'
services:
  v2ray:
    image: v2ray/official:latest 
    container_name: v2ray
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
    ports:
      - "10086:10086"
      - "10086:10086/udp"
      - "10087:10087"
      - "10087:10087/udp"
      - "45000-45001:45000-45001"
      - "45000-45001:45000-45001/udp"
    command: ["v2ray","-config=/etc/v2ray/config.json"]