package main

import (
	"fmt"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

type AutoGenerated struct {
	SdkBuildConfig []SdkBuildConfig `toml:"sdk-build-config"`
}
type List struct {
	ID          string `toml:"id"`
	Description string `toml:"description"`
}
type SdkBuildConfig struct {
	ID           string      `toml:"id"`
	Type         string      `toml:"type"`
	Description  string      `toml:"description"`
	DefaultValue interface{} `toml:"defaultValue,omitempty"`
	List         []List      `toml:"list,omitempty"`
}

func ReadConf(filename string) (*AutoGenerated, error) {
	conf := &AutoGenerated{}
	if _, err := toml.DecodeFile(filename, conf); err != nil {
		return nil, err
	}
	return conf, nil
}

func main() {

	if filename, err := filepath.Abs("./asset/build-config.toml"); err != nil {
		fmt.Println(err)
	} else {
		ReadConf(filename)
	}

}
